// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NayraBase.Infrastructure.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NayraBase.Infrastructure.Migrations
{
    [DbContext(typeof(NayraBaseDbContext))]
    partial class NayraBaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NayraBase.Domain.Entities.ClienteApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.PrimitiveCollection<string[]>("AllowedIps")
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_ips");

                    b.PrimitiveCollection<string[]>("AllowedOrigins")
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_origins");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_secret_hash");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_expiracion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("RateLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("rate_limit");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("timestamp")
                        .HasColumnName("ultimo_uso");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("idx_cliente_api_activo");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("idx_cliente_api_client_id");

                    b.HasIndex("CreadoPor");

                    b.ToTable("clientes_api", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.ClienteApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteApiId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_api_id");

                    b.Property<int?>("DuracionMs")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_ms");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_request")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ClienteApiId")
                        .HasDatabaseName("idx_log_cliente_api");

                    b.HasIndex("ResponseCode")
                        .HasDatabaseName("idx_log_response_code");

                    b.HasIndex("ClienteApiId", "FechaRequest")
                        .HasDatabaseName("idx_log_cliente_fecha");

                    b.ToTable("cliente_api_logs", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<int?>("DependenciaPadreId")
                        .HasColumnType("integer")
                        .HasColumnName("dependencia_padre_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsHoja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_hoja");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.Property<string>("RutaCompleta")
                        .HasColumnType("text")
                        .HasColumnName("ruta_completa");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("idx_dependencia_codigo");

                    b.HasIndex("DependenciaPadreId")
                        .HasDatabaseName("idx_dependencia_padre");

                    b.HasIndex("Nivel")
                        .HasDatabaseName("idx_dependencia_nivel");

                    b.ToTable("dependencias", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.DependenciaPerfilConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int?>("CantidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_maxima");

                    b.Property<int?>("ConfiguradoPor")
                        .HasColumnType("integer")
                        .HasColumnName("configurado_por");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("dependencia_id");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_configuracion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.Property<bool>("RequiereAprobacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_aprobacion");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("DependenciaId", "PerfilId")
                        .IsUnique()
                        .HasDatabaseName("idx_dependencia_perfil_unique");

                    b.ToTable("dependencia_perfil_config", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.ModoHerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_sistema");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FiltroPermisos")
                        .HasColumnType("jsonb")
                        .HasColumnName("filtro_permisos");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<int>("NivelAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("nivel_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<bool>("PermiteAprobaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permite_aprobaciones");

                    b.Property<bool>("PermiteLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("permite_lectura");

                    b.Property<bool>("PermiteOperaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permite_operaciones");

                    b.Property<bool>("PermiteReportes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("permite_reportes");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("idx_modo_herencia_codigo");

                    b.ToTable("modos_herencia", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsOperativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_operativo");

                    b.Property<bool>("EsSupervision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_supervision");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NivelJerarquico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("nivel_jerarquico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_perfil_nombre");

                    b.ToTable("perfiles", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.PerfilPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer")
                        .HasColumnName("permiso_id");

                    b.Property<bool>("PuedeDelegar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("puede_delegar");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("PerfilId", "PermisoId")
                        .IsUnique()
                        .HasDatabaseName("idx_perfil_permiso_unique");

                    b.ToTable("perfil_permiso", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alcance");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_auditoria");

                    b.Property<bool>("EsOperativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_operativo");

                    b.Property<bool>("EsSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_sistema");

                    b.Property<bool>("EsSupervision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_supervision");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modulo");

                    b.Property<int>("NivelSensibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("nivel_sensibilidad");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recurso");

                    b.Property<bool>("RequiereJustificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_justificacion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("idx_permiso_codigo");

                    b.HasIndex("Modulo")
                        .HasDatabaseName("idx_permiso_modulo");

                    b.HasIndex("Recurso")
                        .HasDatabaseName("idx_permiso_recurso");

                    b.ToTable("permisos", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int?>("Genero")
                        .HasColumnType("integer")
                        .HasColumnName("genero");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_persona_email");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("idx_persona_numero_documento");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_revocacion");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reemplazado_por");

                    b.Property<bool>("Revocado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revocado");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_refresh_token_usuario");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.TokenConfirmacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_uso");

                    b.Property<string>("IpAddressUso")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address_uso");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("usado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_token_confirmacion");

                    b.HasIndex("UsuarioId", "Tipo")
                        .HasDatabaseName("idx_token_usuario_tipo");

                    b.ToTable("tokens_confirmacion", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_stamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por");

                    b.Property<bool>("DebeCambiarPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("debe_cambiar_password");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("security_stamp")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_normalized_username");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_persona");

                    b.HasIndex("SecurityStamp")
                        .HasDatabaseName("idx_usuario_security_stamp");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.UsuarioPerfilDependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("asignado_por");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("dependencia_id");

                    b.Property<string>("DocumentoSustento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("documento_sustento");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_fin");

                    b.Property<bool>("HeredaASubdependencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hereda_a_subdependencias");

                    b.Property<int?>("ModoHerenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("modo_herencia_id");

                    b.Property<string>("MotivoAsignacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_asignacion");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.PrimitiveCollection<int[]>("PermisosAdicionales")
                        .HasColumnType("integer[]")
                        .HasColumnName("permisos_adicionales");

                    b.PrimitiveCollection<int[]>("PermisosRevocados")
                        .HasColumnType("integer[]")
                        .HasColumnName("permisos_revocados");

                    b.Property<bool>("SoloLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("solo_lectura");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId")
                        .HasDatabaseName("idx_upd_dependencia");

                    b.HasIndex("ModoHerenciaId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_upd_usuario");

                    b.HasIndex("UsuarioId", "DependenciaId")
                        .HasDatabaseName("idx_upd_usuario_dependencia");

                    b.HasIndex("UsuarioId", "PerfilId", "DependenciaId")
                        .IsUnique()
                        .HasDatabaseName("idx_upd_unique");

                    b.ToTable("usuario_perfil_dependencia", (string)null);
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.ClienteApi", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.ClienteApiLog", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.ClienteApi", "ClienteApi")
                        .WithMany("Logs")
                        .HasForeignKey("ClienteApiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteApi");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Dependencia", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Dependencia", "DependenciaPadre")
                        .WithMany("DependenciasHijas")
                        .HasForeignKey("DependenciaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependenciaPadre");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.DependenciaPerfilConfig", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany("ConfiguracionPerfiles")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NayraBase.Domain.Entities.Perfil", "Perfil")
                        .WithMany("ConfiguracionesDependencias")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.PerfilPermiso", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PerfilPermisos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NayraBase.Domain.Entities.Permiso", "Permiso")
                        .WithMany("PerfilPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.TokenConfirmacion", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TokensConfirmacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("NayraBase.Domain.Entities.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.UsuarioPerfilDependencia", b =>
                {
                    b.HasOne("NayraBase.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NayraBase.Domain.Entities.ModoHerencia", "ModoHerencia")
                        .WithMany("AsignacionesConModo")
                        .HasForeignKey("ModoHerenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NayraBase.Domain.Entities.Perfil", "Perfil")
                        .WithMany("AsignacionesUsuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NayraBase.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PerfilesDependencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");

                    b.Navigation("ModoHerencia");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.ClienteApi", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Dependencia", b =>
                {
                    b.Navigation("ConfiguracionPerfiles");

                    b.Navigation("DependenciasHijas");

                    b.Navigation("UsuariosAsignados");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.ModoHerencia", b =>
                {
                    b.Navigation("AsignacionesConModo");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("AsignacionesUsuarios");

                    b.Navigation("ConfiguracionesDependencias");

                    b.Navigation("PerfilPermisos");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("PerfilPermisos");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NayraBase.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PerfilesDependencias");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TokensConfirmacion");
                });
#pragma warning restore 612, 618
        }
    }
}
